### ISSUE TITLE
example "resolve.conf" file should be renamed to "resolv.conf"

### ISSUE THREAD

**Issue by stlhood** [ksherlock/marignotti#2]
I couldn't figure out why DNS was working perfectly for GS/OS GUI apps but not for GNO shell apps. After much headdesk-ing, I finally realized that Marignotti ships with an example "resolve.conf" file, and the instructions suggest moving and editing that same file. But that file _should_ be named "resolv.conf" (note: no "e"). By copying and editing the file that came with the distro, I unwittingly ended up with a file that GNO wasn't even looking for. It might be good to rename this file so that others don't run into the same problem. :)

**Comment by ksherlock** [comment]
Thank you.  This has been fixed in the new release and in the documentation.

Kelvin
